apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::856138947334:role/eksctl-eksctl-demo-nodegroup-ng-d-NodeInstanceRole-B03KD6DAOG1Y
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::856138947334:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-14T14:33:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1567"
  uid: 77ca60be-9e01-47af-97b4-b4aea74e714d
